// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Код ошибки
	Code *string `json:"code,omitempty"`

	// Message Описание ошибки
	Message *string `json:"message,omitempty"`
}

// EventRequest defines model for EventRequest.
type EventRequest struct {
	// Date Дата и время начала события (RFC3339)
	Date time.Time `json:"date"`

	// Description Описание события (опционально)
	Description *string `json:"description,omitempty"`

	// EndDate Дата и время окончания события (RFC3339)
	EndDate time.Time `json:"end_date"`

	// NotifyBefore За сколько времени высылать уведомление в Go duration format (опционально). Примеры: "24h", "30m", "1h30m"
	NotifyBefore *string `json:"notify_before,omitempty"`

	// Title Заголовок события
	Title string `json:"title"`

	// UserId ID пользователя - владельца события (UUID)
	UserId openapi_types.UUID `json:"user_id"`
}

// EventResponse defines model for EventResponse.
type EventResponse struct {
	// Date Дата и время начала события (RFC3339)
	Date *time.Time `json:"date,omitempty"`

	// Description Описание события
	Description *string `json:"description,omitempty"`

	// EndDate Дата и время окончания события (RFC3339)
	EndDate *time.Time `json:"end_date,omitempty"`

	// Id Уникальный идентификатор события
	Id *openapi_types.UUID `json:"id,omitempty"`

	// NotifyBefore За сколько времени высылать уведомление (duration format)
	NotifyBefore *string `json:"notify_before,omitempty"`

	// Title Заголовок события
	Title *string `json:"title,omitempty"`

	// UserId ID пользователя - владельца события (UUID)
	UserId *openapi_types.UUID `json:"user_id,omitempty"`
}

// ListEventsDayParams defines parameters for ListEventsDay.
type ListEventsDayParams struct {
	// Date Дата в формате RFC3339
	Date time.Time `form:"date" json:"date"`
}

// ListEventsMonthParams defines parameters for ListEventsMonth.
type ListEventsMonthParams struct {
	// Date Дата начала месяца в формате RFC3339
	Date time.Time `form:"date" json:"date"`
}

// ListEventsWeekParams defines parameters for ListEventsWeek.
type ListEventsWeekParams struct {
	// Date Дата начала недели в формате RFC3339
	Date time.Time `form:"date" json:"date"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventRequest

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = EventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать событие
	// (POST /events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// Получить список событий на день
	// (GET /events/day)
	ListEventsDay(w http.ResponseWriter, r *http.Request, params ListEventsDayParams)
	// Получить список событий на месяц
	// (GET /events/month)
	ListEventsMonth(w http.ResponseWriter, r *http.Request, params ListEventsMonthParams)
	// Получить список событий на неделю
	// (GET /events/week)
	ListEventsWeek(w http.ResponseWriter, r *http.Request, params ListEventsWeekParams)
	// Удалить событие
	// (DELETE /events/{id})
	DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Обновить событие
	// (PUT /events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Создать событие
// (POST /events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список событий на день
// (GET /events/day)
func (_ Unimplemented) ListEventsDay(w http.ResponseWriter, r *http.Request, params ListEventsDayParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список событий на месяц
// (GET /events/month)
func (_ Unimplemented) ListEventsMonth(w http.ResponseWriter, r *http.Request, params ListEventsMonthParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список событий на неделю
// (GET /events/week)
func (_ Unimplemented) ListEventsWeek(w http.ResponseWriter, r *http.Request, params ListEventsWeekParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить событие
// (DELETE /events/{id})
func (_ Unimplemented) DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить событие
// (PUT /events/{id})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEventsDay operation middleware
func (siw *ServerInterfaceWrapper) ListEventsDay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsDayParams

	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventsDay(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEventsMonth operation middleware
func (siw *ServerInterfaceWrapper) ListEventsMonth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsMonthParams

	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventsMonth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEventsWeek operation middleware
func (siw *ServerInterfaceWrapper) ListEventsWeek(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsWeekParams

	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventsWeek(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/day", wrapper.ListEventsDay)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/month", wrapper.ListEventsMonth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/week", wrapper.ListEventsWeek)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/events/{id}", wrapper.DeleteEvent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/events/{id}", wrapper.UpdateEvent)
	})

	return r
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201JSONResponse EventResponse

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvent400JSONResponse ErrorResponse

func (response CreateEvent400JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvent500JSONResponse ErrorResponse

func (response CreateEvent500JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsDayRequestObject struct {
	Params ListEventsDayParams
}

type ListEventsDayResponseObject interface {
	VisitListEventsDayResponse(w http.ResponseWriter) error
}

type ListEventsDay200JSONResponse []EventResponse

func (response ListEventsDay200JSONResponse) VisitListEventsDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsDay400JSONResponse ErrorResponse

func (response ListEventsDay400JSONResponse) VisitListEventsDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsDay500JSONResponse ErrorResponse

func (response ListEventsDay500JSONResponse) VisitListEventsDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsMonthRequestObject struct {
	Params ListEventsMonthParams
}

type ListEventsMonthResponseObject interface {
	VisitListEventsMonthResponse(w http.ResponseWriter) error
}

type ListEventsMonth200JSONResponse []EventResponse

func (response ListEventsMonth200JSONResponse) VisitListEventsMonthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsMonth400JSONResponse ErrorResponse

func (response ListEventsMonth400JSONResponse) VisitListEventsMonthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsMonth500JSONResponse ErrorResponse

func (response ListEventsMonth500JSONResponse) VisitListEventsMonthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsWeekRequestObject struct {
	Params ListEventsWeekParams
}

type ListEventsWeekResponseObject interface {
	VisitListEventsWeekResponse(w http.ResponseWriter) error
}

type ListEventsWeek200JSONResponse []EventResponse

func (response ListEventsWeek200JSONResponse) VisitListEventsWeekResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsWeek400JSONResponse ErrorResponse

func (response ListEventsWeek400JSONResponse) VisitListEventsWeekResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsWeek500JSONResponse ErrorResponse

func (response ListEventsWeek500JSONResponse) VisitListEventsWeekResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEventRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteEventResponseObject interface {
	VisitDeleteEventResponse(w http.ResponseWriter) error
}

type DeleteEvent204Response struct {
}

func (response DeleteEvent204Response) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEvent404JSONResponse ErrorResponse

func (response DeleteEvent404JSONResponse) VisitDeleteEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteEvent500JSONResponse ErrorResponse

func (response DeleteEvent500JSONResponse) VisitDeleteEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateEventRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateEventJSONRequestBody
}

type UpdateEventResponseObject interface {
	VisitUpdateEventResponse(w http.ResponseWriter) error
}

type UpdateEvent200JSONResponse EventResponse

func (response UpdateEvent200JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateEvent400JSONResponse ErrorResponse

func (response UpdateEvent400JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateEvent404JSONResponse ErrorResponse

func (response UpdateEvent404JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateEvent500JSONResponse ErrorResponse

func (response UpdateEvent500JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Создать событие
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// Получить список событий на день
	// (GET /events/day)
	ListEventsDay(ctx context.Context, request ListEventsDayRequestObject) (ListEventsDayResponseObject, error)
	// Получить список событий на месяц
	// (GET /events/month)
	ListEventsMonth(ctx context.Context, request ListEventsMonthRequestObject) (ListEventsMonthResponseObject, error)
	// Получить список событий на неделю
	// (GET /events/week)
	ListEventsWeek(ctx context.Context, request ListEventsWeekRequestObject) (ListEventsWeekResponseObject, error)
	// Удалить событие
	// (DELETE /events/{id})
	DeleteEvent(ctx context.Context, request DeleteEventRequestObject) (DeleteEventResponseObject, error)
	// Обновить событие
	// (PUT /events/{id})
	UpdateEvent(ctx context.Context, request UpdateEventRequestObject) (UpdateEventResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(w http.ResponseWriter, r *http.Request) {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx, request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		if err := validResponse.VisitCreateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEventsDay operation middleware
func (sh *strictHandler) ListEventsDay(w http.ResponseWriter, r *http.Request, params ListEventsDayParams) {
	var request ListEventsDayRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventsDay(ctx, request.(ListEventsDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventsDay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsDayResponseObject); ok {
		if err := validResponse.VisitListEventsDayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEventsMonth operation middleware
func (sh *strictHandler) ListEventsMonth(w http.ResponseWriter, r *http.Request, params ListEventsMonthParams) {
	var request ListEventsMonthRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventsMonth(ctx, request.(ListEventsMonthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventsMonth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsMonthResponseObject); ok {
		if err := validResponse.VisitListEventsMonthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEventsWeek operation middleware
func (sh *strictHandler) ListEventsWeek(w http.ResponseWriter, r *http.Request, params ListEventsWeekParams) {
	var request ListEventsWeekRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventsWeek(ctx, request.(ListEventsWeekRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventsWeek")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsWeekResponseObject); ok {
		if err := validResponse.VisitListEventsWeekResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEvent operation middleware
func (sh *strictHandler) DeleteEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEvent(ctx, request.(DeleteEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEventResponseObject); ok {
		if err := validResponse.VisitDeleteEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateEvent operation middleware
func (sh *strictHandler) UpdateEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateEventRequestObject

	request.Id = id

	var body UpdateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEvent(ctx, request.(UpdateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateEventResponseObject); ok {
		if err := validResponse.VisitUpdateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
